/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package xingqi_java.GUI;

/**
 *
 * @author TRUNG
 */
public class GameWindow extends javax.swing.JFrame {

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BoardPanel = new javax.swing.JPanel();
        TimePanel = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Player1 = new javax.swing.JPanel();
        NumberPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NumberPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Player2 = new javax.swing.JPanel();
        NumberPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NumberPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LogPanel = new javax.swing.JPanel();
        logheader = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 750));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        BoardPanel.setBackground(new java.awt.Color(204, 204, 204));
        BoardPanel.setMinimumSize(new java.awt.Dimension(700, 700));
        BoardPanel.setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout BoardPanelLayout = new javax.swing.GroupLayout(BoardPanel);
        BoardPanel.setLayout(BoardPanelLayout);
        BoardPanelLayout.setHorizontalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BoardPanelLayout.setVerticalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(BoardPanel, gridBagConstraints);

        TimePanel.setBackground(new java.awt.Color(255, 255, 255));
        TimePanel.setMinimumSize(new java.awt.Dimension(300, 275));
        TimePanel.setPreferredSize(new java.awt.Dimension(300, 275));
        TimePanel.setLayout(new java.awt.GridLayout(3, 0));

        header.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setText("TIMER");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        TimePanel.add(header);

        Player1.setMaximumSize(new java.awt.Dimension(300, 60));
        Player1.setMinimumSize(new java.awt.Dimension(300, 60));
        Player1.setPreferredSize(new java.awt.Dimension(300, 60));
        Player1.setLayout(new java.awt.GridBagLayout());

        NumberPanel2.setMaximumSize(new java.awt.Dimension(150, 80));
        NumberPanel2.setMinimumSize(new java.awt.Dimension(150, 80));
        NumberPanel2.setPreferredSize(new java.awt.Dimension(150, 80));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Player 1:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout NumberPanel2Layout = new javax.swing.GroupLayout(NumberPanel2);
        NumberPanel2.setLayout(NumberPanel2Layout);
        NumberPanel2Layout.setHorizontalGroup(
            NumberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NumberPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        NumberPanel2Layout.setVerticalGroup(
            NumberPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Player1.add(NumberPanel2, gridBagConstraints);

        NumberPanel1.setMaximumSize(new java.awt.Dimension(150, 80));
        NumberPanel1.setMinimumSize(new java.awt.Dimension(150, 80));
        NumberPanel1.setPreferredSize(new java.awt.Dimension(150, 80));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel3.setText("10:00");

        javax.swing.GroupLayout NumberPanel1Layout = new javax.swing.GroupLayout(NumberPanel1);
        NumberPanel1.setLayout(NumberPanel1Layout);
        NumberPanel1Layout.setHorizontalGroup(
            NumberPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        NumberPanel1Layout.setVerticalGroup(
            NumberPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Player1.add(NumberPanel1, new java.awt.GridBagConstraints());

        TimePanel.add(Player1);

        Player2.setMaximumSize(new java.awt.Dimension(300, 108));
        Player2.setMinimumSize(new java.awt.Dimension(300, 108));
        Player2.setLayout(new java.awt.GridBagLayout());

        NumberPanel3.setMaximumSize(new java.awt.Dimension(150, 80));
        NumberPanel3.setMinimumSize(new java.awt.Dimension(150, 80));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Player 2:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout NumberPanel3Layout = new javax.swing.GroupLayout(NumberPanel3);
        NumberPanel3.setLayout(NumberPanel3Layout);
        NumberPanel3Layout.setHorizontalGroup(
            NumberPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NumberPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        NumberPanel3Layout.setVerticalGroup(
            NumberPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Player2.add(NumberPanel3, gridBagConstraints);

        NumberPanel4.setMaximumSize(new java.awt.Dimension(150, 80));
        NumberPanel4.setMinimumSize(new java.awt.Dimension(150, 80));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel5.setText("10:00");

        javax.swing.GroupLayout NumberPanel4Layout = new javax.swing.GroupLayout(NumberPanel4);
        NumberPanel4.setLayout(NumberPanel4Layout);
        NumberPanel4Layout.setHorizontalGroup(
            NumberPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        NumberPanel4Layout.setVerticalGroup(
            NumberPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Player2.add(NumberPanel4, new java.awt.GridBagConstraints());

        TimePanel.add(Player2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        getContentPane().add(TimePanel, gridBagConstraints);

        LogPanel.setBackground(new java.awt.Color(0, 0, 204));
        LogPanel.setMinimumSize(new java.awt.Dimension(300, 375));
        LogPanel.setPreferredSize(new java.awt.Dimension(300, 375));
        LogPanel.setLayout(new java.awt.GridBagLayout());

        logheader.setMinimumSize(new java.awt.Dimension(300, 20));
        logheader.setPreferredSize(new java.awt.Dimension(300, 60));
        logheader.setLayout(new java.awt.GridLayout());

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Game Log");
        logheader.add(jLabel6);

        LogPanel.add(logheader, new java.awt.GridBagConstraints());

        jPanel2.setMinimumSize(new java.awt.Dimension(300, 315));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 315));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton1.setText("End Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        LogPanel.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(14, 2, 14, 2);
        getContentPane().add(LogPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JPanel LogPanel;
    private javax.swing.JPanel NumberPanel1;
    private javax.swing.JPanel NumberPanel2;
    private javax.swing.JPanel NumberPanel3;
    private javax.swing.JPanel NumberPanel4;
    private javax.swing.JPanel Player1;
    private javax.swing.JPanel Player2;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel logheader;
    // End of variables declaration//GEN-END:variables
}
